server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: root
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: true
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        # dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  h2.console.enabled: true # the JDBC URL is jdbc:h2:mem:testdb

security:
  jwt:
    token:
      # generate at https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx
      secret-key: eThWmZq4t7w!z%C*F-JaNdRgUjXn2r5u8x/A?D(G+KbPeShVmYp3s6v9y$B&E)H@
      expire-length: 3600000 # 60 minutes duration by default: 60 minutes * 60 seconds * 1000 milliseconds
